jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MariaDBDialect
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql