file:
  dir: "D:/NAS/rcd/evidence"

spring:
  config:
    import: application-oauth.yml, application-s3.yml, application-jwt.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rcd?useSSL=false&serverTimezone=UTC
    username: root
    password: 89940775

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect # MySQL 사용
        format_sql: true
        show_sql: true
  web:
    resources:
      static-locations: classpath:/static/
