
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

file:
  dir: "D:/NAS/rcd/evidence"

spring:
  config:
    import: application-oauth.yml, application-s3.yml
#  sql:
#    init:
#      mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true # embededDB에 data.sql 사용하기 위함
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MariaDBDialect
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  web:
    resources:
      static-locations: classpath:/static/

