
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (1L, 30, 'desc', 2, 'P', '사진 인증', 'ti2tle');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (2L, 30, 'desc', 2, 'P', '사진 인증', 'title2');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (3L, 30, 'desc', 2, 'P', '사진 인증', 'title3');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (4L, 30, 'desc', 2, 'P', '사진 인증', 'title4');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (5L, 30, 'desc', 2, 'P', '사진 인증', 'title5');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (6L, 30, 'desc', 2, 'P', '사진 인증', 'title6');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (7L, 30, 'desc', 2, 'P', '사진 인증', 'title7');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (8L, 30, 'desc', 2, 'P', '사진 인증', 'title8');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (9L, 30, 'desc', 2, 'P', '사진 인증', 'title9');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (10L, 30, 'desc', 2, 'P', '사진 인증', 'titleq');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (11L, 30, 'desc', 2, 'P', '사진 인증', 'titlew');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (12L, 30, 'desc', 2, 'P', '사진 인증', 'titlee');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (13L, 30, 'desc', 2, 'P', '사진 인증', 'titler');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (14L, 30, 'desc', 2, 'P', '사진 인증', 'titlet');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (15L, 30, 'desc', 2, 'P', '사진 인증', 'titley');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (16L, 30, 'desc', 2, 'P', '사진 인증', 'titleu');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (17L, 30, 'desc', 2, 'P', '사진 인증', 'titlei');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (18L, 30, 'desc', 2, 'P', '사진 인증', 'titleo');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (19L, 30, 'desc', 2, 'P', '사진 인증', 'titlep');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (20L, 30, 'desc', 2, 'P', '사진 인증', 'titlea');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (21L, 30, 'desc', 2, 'P', '사진 인증', 'titles');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (22L, 30, 'desc', 2, 'P', '사진 인증', 'titled');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (23L, 30, 'desc', 2, 'P', '사진 인증', 'titlef');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (24L, 30, 'desc', 2, 'P', '사진 인증', 'titleg');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (25L, 30, 'desc', 2, 'P', '사진 인증', 'titdle');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (26L, 30, 'desc', 2, 'P', '사진 인증', 'titleh');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (27L, 30, 'desc', 2, 'P', '사진 인증', 'titlej');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (28L, 30, 'desc', 2, 'P', '사진 인증', 'titlke');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (29L, 30, 'desc', 2, 'P', '사진 인증', 'titlle');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (30L, 30, 'desc', 2, 'P', '사진 인증', 'titlze');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (31L, 30, 'desc', 2, 'P', '사진 인증', 'titlxe');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (32L, 30, 'desc', 2, 'P', '사진 인증', 'titlcve');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (33L, 30, 'desc', 2, 'P', '사진 인증', 'tid3tle');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (34L, 30, 'desc', 2, 'P', '사진 인증', 'titleb');
insert into challenge_card (id, assign_score, description, difficulty, evidence_type, final_goal, title) values (35L, 30, 'desc', 2, 'P', '사진 인증', 'titlse');

insert into challenge_card_sub_goal (id, challenge_id, intermediate_goal) values (1L, 35L, '중간 목표1');
insert into challenge_card_sub_goal (id, challenge_id, intermediate_goal) values (2L, 35L, '중간 목표2');
insert into challenge_card_sub_goal (id, challenge_id, intermediate_goal) values (3L, 35L, '중간 목표3');